# Generated by Django 4.2.2 on 2023-10-24 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establishment', '0008_rename_establishmentmodel_establishment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(help_text='Final audit rating')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('numOfQuestions', models.IntegerField()),
                ('scoreToPass', models.IntegerField()),
                ('auditory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditory.audit')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditory.section')),
            ],
        ),
        migrations.CreateModel(
            name='EstablishmentAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment', models.ManyToManyField(to='establishment.establishment')),
            ],
        ),
        migrations.AddField(
            model_name='audit',
            name='establishmentAudit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditory.establishmentaudit'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('correct', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditory.question')),
            ],
        ),
    ]
