# Generated by Django 4.2.2 on 2023-10-24 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audit',
            old_name='rating',
            new_name='scoreToPass',
        ),
        migrations.RemoveField(
            model_name='section',
            name='auditory',
        ),
    ]
