# Generated by Django 4.2.2 on 2023-10-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0008_rename_establishmentmodel_establishment'),
        ('auditory', '0003_sectionresult_auditresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditresult',
            old_name='rating',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='sectionresult',
            old_name='rating',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='establishmentAudit',
        ),
        migrations.AddField(
            model_name='audit',
            name='establishment',
            field=models.ManyToManyField(to='establishment.establishment'),
        ),
        migrations.AddField(
            model_name='audit',
            name='secciones',
            field=models.ManyToManyField(to='auditory.section'),
        ),
        migrations.DeleteModel(
            name='EstablishmentAudit',
        ),
    ]
