# Generated by Django 4.2.2 on 2023-10-26 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0008_rename_establishmentmodel_establishment'),
        ('auditory', '0004_rename_rating_auditresult_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audit',
            name='secciones',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='establishment',
        ),
        migrations.CreateModel(
            name='EstablishmentAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment', models.ManyToManyField(to='establishment.establishment')),
            ],
        ),
        migrations.AddField(
            model_name='audit',
            name='establishment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auditory.establishmentaudit'),
        ),
    ]
