# Generated by Django 4.2.2 on 2023-10-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0008_rename_establishmentmodel_establishment'),
        ('auditory', '0005_remove_audit_secciones_remove_audit_establishment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audit',
            name='establishment',
        ),
        migrations.DeleteModel(
            name='EstablishmentAudit',
        ),
        migrations.AddField(
            model_name='audit',
            name='establishment',
            field=models.ManyToManyField(to='establishment.establishment'),
        ),
    ]
