# Generated by Django 4.2.2 on 2023-10-31 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auditory', '0007_audit_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/audits/')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditory.audit')),
            ],
        ),
    ]
