# Generated by Django 4.2.2 on 2023-11-17 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditory', '0008_auditfile_sectionresult_audit_delete_auditresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditFile',
        ),
    ]
