# Generated by Django 4.2.2 on 2023-11-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditory', '0009_delete_auditfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='scoreToPass',
            field=models.IntegerField(),
        ),
    ]
