# Generated by Django 4.2.5 on 2023-09-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('last_name', models.CharField(max_length=100, null=True, verbose_name='last name')),
                ('No_Id', models.BigIntegerField(null=True, verbose_name='No Id')),
                ('mail', models.CharField(max_length=50, null=True, verbose_name='mail')),
                ('passkey', models.CharField(max_length=10, null=True, verbose_name='passkey')),
                ('cell_phone', models.CharField(max_length=10, null=True, verbose_name='phone')),
            ],
        ),
    ]
