# Generated by Django 4.2.5 on 2023-09-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditor',
            name='No_Id',
            field=models.BigIntegerField(null=True, verbose_name='No° Id'),
        ),
    ]
