# Generated by Django 4.2.2 on 2023-10-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, null=True, verbose_name='Apellido')),
                ('No_Id', models.BigIntegerField(null=True, verbose_name='No° Id')),
                ('mail', models.EmailField(max_length=50, null=True, verbose_name='Correo')),
                ('passkey', models.CharField(max_length=10, null=True, verbose_name='Clave')),
                ('cell_phone_number', models.BigIntegerField(null=True, verbose_name='Celular')),
            ],
        ),
    ]
