# Generated by Django 4.2.2 on 2023-10-02 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditor',
            old_name='No_Id',
            new_name='no_id',
        ),
    ]
