# Generated by Django 4.2.2 on 2023-10-05 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_no_id_auditor_no_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auditor',
        ),
    ]
