# Generated by Django 4.2.2 on 2023-09-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='address',
            field=models.CharField(max_length=50, null=True, verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='contact',
            field=models.BigIntegerField(null=True, verbose_name='Contacto'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='imagen'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='mail',
            field=models.CharField(max_length=50, null=True, verbose_name='Correo'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='website',
            field=models.CharField(max_length=100, null=True, verbose_name='Pagina Web'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='rut',
            field=models.BigIntegerField(null=True, verbose_name='RUT'),
        ),
    ]
