# Generated by Django 4.2.2 on 2023-09-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0003_remove_establishment_image_establishment_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/hotelProfile', verbose_name='Foto del Establecimiento'),
        ),
    ]
