# Generated by Django 4.2.2 on 2023-10-02 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0004_alter_establishment_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Establishment',
            new_name='Hotel',
        ),
    ]
