# Generated by Django 4.2.2 on 2023-10-17 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0007_rename_establishment_establishmentmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EstablishmentModel',
            new_name='Establishment',
        ),
    ]
